
# Nombre de la aplicación
spring.application.name=franquicias

# Configuración de R2DBC
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/franquicias
spring.r2dbc.username=postgres
spring.r2dbc.password=admin


logging.level.org.springframework.r2dbc=DEBUG
